### ISSUE TITLE
Vendor `simtk` unit to string code

### ISSUE THREAD

**Issue by SimonBoothroyd** [mattwthompson/openff-units#3]
## Description

Currently the `utils` module imports the [`unit_to_string`](https://github.com/mattwthompson/openff-units/blob/0d9d906b325fea0411fb4f4a0aea06cfc8ca813e/openff/units/utils.py#L26) method from the [OpenFF toolkit](https://github.com/openforcefield/openff-toolkit/blob/24953a407c853411bee9584d29fa0fb953e59151/openff/toolkit/utils/utils.py#L208). It would seem however best to just vendor it here instead given that the TK would likely eventually depend on this package.

**Comment by mattwthompson** [comment]
I agree this would be the right change to make.

How should I go about doing this? i.e. what besides copy-pasting the code and modifying it to fit here?

**Comment by SimonBoothroyd** [comment]
> How should I go about doing this? i.e. what besides copy-pasting the code and modifying it to fit here?

I think basically just copy + paste the code + associated test and should be good!
